### ISSUE TITLE
Upload this library to luarocks for building with rocks.nvim

### ISSUE THREAD

**Issue by neo451** [gregorias/coop.nvim#5]
I recently adopted this library in my feed reader plugin: https://github.com/neo451/feed.nvim
but upon pushing this new release I found that it could not automatically build and publish to luarocks because this library is not on there. 
here are some references on how to set it up:
https://github.com/nvim-neorocks/sample-luarocks-plugin
https://github.com/nvim-neorocks/luarocks-tag-release

would really appreciate it, and I can pr in the changes as well after you set up the repo keys.

**Comment by gregorias** [comment]
SGTM to support releases to Luarocks. I’ll work on this soonish (in a day?). That PR would be appreciated.

**Comment by gregorias** [comment]
I’ve concocted https://github.com/gregorias/coop.nvim/pull/6/files and published an artifact to LuaRocks.

Could I ask you, @neo451, to review the PR? I don’t want to do the GitHub actions from https://github.com/nvim-neorocks/sample-luarocks-plugin, because I want to gain some know-how of how things work under the hood before I use some magical commands + I want to have a smaller dependency footprint.

**Comment by neo451** [comment]
I would not say i am very qualified to review it though, cause I only once published something on luarocks without making a new release ever again lol. But the PR looks very clean and on point, and I also tested it both locally and on my plugin's github action, so I think it is good enough. Thank you for your awesome work.
